---

- include: Debian.yml
  when: ansible_os_family == "Debian"

- name: Clone Certbot into configured directory.
  git:
    repo: "{{ certbot_repo }}"
    dest: "{{ certbot_dir }}"
    version: "{{ certbot_version }}"
    update: "{{ certbot_keep_updated }}"
    force: yes
  tags: clone_certbot_repo

- name: Ensure certbot-auto is executable.
  file:
    path: "{{ certbot_dir }}/certbot-auto"
    mode: 0755

- name: Create public directories
  file:
    path: "{{item.root_dir}}"
    mode: 0750
    owner: "www-data"
    group: "www-data"
    state: directory
  with_items: certbot_domains

- name: configuration files
  template:
    src: config.ini.j2
    dest: /etc/certbot-{{item.main}}.conf
    mode: 0755
  with_items: certbot_domains
  tags: certbot_generate_conf

- name: generate certificates
  shell: "{{certbot_dir}}/certbot-auto certonly -c /etc/certbot-{{item.main}}.conf"
  with_items: certbot_domains
#  when: not ansible_check_mode
  tags: generate_letsencrypt_certs

#- name: generate certificates
#  shell: "{{certbot_dir}}/certbot-auto certonly -c /etc/certbot-{{item.main}}.conf --dry-run"
#  with_items: certbot_domains
#  when: ansible_check_mode
#  tags: generate_letsencrypt_certs

- name: generate cronjobs
  template:
    src: cron.j2
    dest: "/etc/cron.d/certbot-{{ item.main }}"
    owner: root
    mode: 0644
  with_items: certbot_domains
  tags: certbot_generate_cron_renew_tasks
